set nocompatible              " be iMproved, required --- "

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'rust-lang/rust.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'https://github.com/leafgarland/typescript-vim.git'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'dart-lang/dart-vim-plugin'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'cespare/vim-toml'
Plugin 'elixir-editors/vim-elixir'
Plugin 'scrooloose/nerdcommenter'
Plugin 'w0rp/ale'

call vundle#end()            " required --- "
filetype plugin indent on    " required --- "

set number relativenumber
syntax on

let &colorcolumn=join(range(80,999),",")
let g:indentLine_color_term = 255
let g:tablineclosebutton=1
highlight ColorColumn ctermbg=234 guibg=#FFFFFF
let g:indentLine_setColors = 0
set incsearch
set hlsearch
set cindent
set ignorecase
set cursorline
set background=dark
set ff=unix
set t_co=256
set tabstop=4
set shiftwidth=4
set expandtab
set undofile
set undodir=~/.vim/undodir
set clipboard=unnamed
let g:ycm_use_clangd = 0
let g:NERDSpaceDelims = 1
let g:autofmt_autosave = 1
set rtp+=/usr/local/opt/fzf

" Remap Keys --- "
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
inoremap jk <Esc>
map <silent> <C-n> :NERDTreeToggle<CR>


if !exists("g:ycm_semantic_triggers")
    let g:ycm_semantic_triggers = {}
endif

" Uncomment to open NERDTree by default.
" autocmd vimenter * NERDTree | wincmd w
